// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Ways::readAllWays
int Ways::readAllWays(std::string osmWays);
RcppExport SEXP osm-router_Ways::readAllWays(SEXP osmWaysSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type osmWays(osmWaysSEXP);
    __result = Rcpp::wrap(Ways::readAllWays(osmWays));
    return __result;
END_RCPP
}
